// Fallback questions used when AI generation is unavailable.
// 20 theatre-themed questions, difficulty balanced across easy/medium/hard.

import { QuizQuestionInternal } from '@/lib/types';

export const FALLBACK_QUESTIONS: Omit<QuizQuestionInternal, 'id' | 'index'>[] = [
  {
    text: 'Which Shakespeare play features the line "To be, or not to be, that is the question"?',
    options: ['Macbeth', 'Hamlet', 'Othello', 'King Lear'],
    correctAnswerIndex: 1,
    difficulty: 'easy',
    theme: 'Shakespeare',
  },
  {
    text: 'What is the term for the area of a stage that is closest to the audience?',
    options: ['Upstage', 'Centre stage', 'Downstage', 'Wings'],
    correctAnswerIndex: 2,
    difficulty: 'easy',
    theme: 'Stage Terminology',
  },
  {
    text: 'Which musical features the song "Memory"?',
    options: ['Chicago', 'Cats', 'Phantom of the Opera', 'Les Misérables'],
    correctAnswerIndex: 1,
    difficulty: 'easy',
    theme: 'Musicals',
  },
  {
    text: 'What does a stage manager call out before the show begins to warn actors to take positions?',
    options: ['Break a leg', 'Places please', 'Curtain up', 'House lights'],
    correctAnswerIndex: 1,
    difficulty: 'easy',
    theme: 'Stage Terminology',
  },
  {
    text: 'The phrase "break a leg" in theatre traditionally means:',
    options: ['Perform badly on purpose', 'Good luck', 'Wait in the wings', 'Hit your mark'],
    correctAnswerIndex: 1,
    difficulty: 'easy',
    theme: 'Theatre Culture',
  },
  {
    text: 'Which ancient Greek playwright wrote "Oedipus Rex"?',
    options: ['Aeschylus', 'Euripides', 'Aristophanes', 'Sophocles'],
    correctAnswerIndex: 3,
    difficulty: 'medium',
    theme: 'Classical Theatre',
  },
  {
    text: 'What is a "soliloquy" in theatre?',
    options: [
      'A duet between two characters',
      'A speech given by one character alone to reveal inner thoughts',
      'A dance sequence without dialogue',
      'A monologue delivered to another character',
    ],
    correctAnswerIndex: 1,
    difficulty: 'medium',
    theme: 'Dramatic Terms',
  },
  {
    text: 'The theatrical concept "Brechtian" is associated with which playwright?',
    options: ['Anton Chekhov', 'Bertolt Brecht', 'Samuel Beckett', 'Henrik Ibsen'],
    correctAnswerIndex: 1,
    difficulty: 'medium',
    theme: 'Theatre History',
  },
  {
    text: 'What is the "fourth wall" in theatre?',
    options: [
      'The back wall of the stage set',
      'The imaginary barrier between performers and the audience',
      'The wall behind the wings',
      'The technical lighting grid',
    ],
    correctAnswerIndex: 1,
    difficulty: 'medium',
    theme: 'Dramatic Terms',
  },
  {
    text: 'Which Nigerian playwright wrote "Death and the King\'s Horseman"?',
    options: ['Ola Rotimi', 'Femi Osofisan', 'Wole Soyinka', 'John Pepper Clark'],
    correctAnswerIndex: 2,
    difficulty: 'medium',
    theme: 'African Theatre',
  },
  {
    text: 'In Yoruba theatre tradition, the "Alarinjo" are best described as:',
    options: [
      'Professional critics hired by the court',
      'Travelling masquerade performers',
      'Court musicians playing talking drums',
      'Sacred ritual priests',
    ],
    correctAnswerIndex: 1,
    difficulty: 'medium',
    theme: 'African Theatre',
  },
  {
    text: 'Which of these is NOT a play by Samuel Beckett?',
    options: ['Waiting for Godot', 'Endgame', 'Krapp\'s Last Tape', 'The Birthday Party'],
    correctAnswerIndex: 3,
    difficulty: 'medium',
    theme: 'Theatre History',
  },
  {
    text: 'What is "in medias res" as a dramatic device?',
    options: [
      'Starting the narrative in the middle of the action',
      'Ending with an unresolved conflict',
      'Using a narrator to frame the story',
      'Repeating a scene from a different character\'s perspective',
    ],
    correctAnswerIndex: 0,
    difficulty: 'hard',
    theme: 'Dramatic Terms',
  },
  {
    text: 'Which staging configuration places the audience on all four sides of the performance space?',
    options: ['Thrust stage', 'Proscenium', 'Theatre-in-the-round', 'Traverse stage'],
    correctAnswerIndex: 2,
    difficulty: 'hard',
    theme: 'Stage Design',
  },
  {
    text: 'Stanislavski\'s "System" primarily focused on which acting technique?',
    options: [
      'Physical comedy and clowning',
      'Emotional memory and psychological truth',
      'Mask work and non-verbal expression',
      'Verse speaking and heightened language',
    ],
    correctAnswerIndex: 1,
    difficulty: 'hard',
    theme: 'Acting Theory',
  },
  {
    text: 'The term "dramaturgy" most precisely refers to:',
    options: [
      'The craft of scenic design',
      'The study and practice of dramatic composition and theatrical structure',
      'The training of actors in movement',
      'The design of theatrical lighting',
    ],
    correctAnswerIndex: 1,
    difficulty: 'hard',
    theme: 'Dramatic Terms',
  },
  {
    text: 'Ola Rotimi\'s adaptation of Oedipus Rex is titled:',
    options: ['The Gods Are Not To Blame', 'Our Husband Has Gone Mad Again', 'Ovonramwen Nogbaisi', 'Kurunmi'],
    correctAnswerIndex: 0,
    difficulty: 'hard',
    theme: 'African Theatre',
  },
  {
    text: 'In Aristotle\'s "Poetics", which element of tragedy does he rank most important?',
    options: ['Character', 'Diction', 'Plot (Mythos)', 'Spectacle'],
    correctAnswerIndex: 2,
    difficulty: 'hard',
    theme: 'Classical Theatre',
  },
  {
    text: 'The "unities" of classical theatre doctrine refer to unity of:',
    options: [
      'Character, conflict, and resolution',
      'Action, time, and place',
      'Language, movement, and design',
      'Theme, plot, and subplot',
    ],
    correctAnswerIndex: 1,
    difficulty: 'hard',
    theme: 'Classical Theatre',
  },
  {
    text: 'What is "peripateia" in classical drama?',
    options: [
      'The moment of tragic recognition',
      'A sudden reversal of fortune for the protagonist',
      'The choral interlude between episodes',
      'The final speech before the chorus exits',
    ],
    correctAnswerIndex: 1,
    difficulty: 'hard',
    theme: 'Classical Theatre',
  },
];
