'use client';

import React from 'react';
import Link from 'next/link';
import { ArrowLeft, FileText, Scale, UserCheck, AlertTriangle } from 'lucide-react';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-white py-16 px-4 md:px-8">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-white transition-colors mb-8">
          <ArrowLeft className="h-4 w-4" /> Back to Home
        </Link>

        <div className="mb-12 animate-fade-down">
          <span className="text-xs bg-red-600/10 text-red-400 border border-red-600/25 px-3 py-1 rounded-full uppercase tracking-wider font-semibold">
            Legal Policy
          </span>
          <h1 className="text-4xl md:text-5xl font-serif font-bold text-white mt-4 mb-6">
            Terms of Service
          </h1>
          <p className="text-zinc-400 text-base leading-relaxed font-light">
            Effective Date: May 24, 2026. These terms govern your use of the Curtain Call platform, including ticket purchases, content submission, and profile management.
          </p>
        </div>

        {/* Content Panels */}
        <div className="flex flex-col gap-8 mb-12 animate-fade-up">
          
          <div className="bg-zinc-900/40 border border-white/5 rounded-3xl p-6 md:p-8 backdrop-blur-md">
            <h2 className="text-xl font-serif font-bold text-white mb-4 flex items-center gap-2">
              <UserCheck className="h-5 w-5 text-blue-400" />
              1. User Accounts & Identity
            </h2>
            <p className="text-zinc-400 text-sm leading-relaxed mb-4">
              To buy tickets, submit articles, or claim a professional profile on Curtain Call, you must register for an account. You agree to provide accurate, current, and complete information. You are solely responsible for maintaining the confidentiality of your account credentials.
            </p>
            <p className="text-zinc-400 text-sm leading-relaxed">
              Curtain Call reserves the right to suspend or terminate accounts that engage in fraudulent activity, impersonation, or violation of these terms.
            </p>
          </div>

          <div className="bg-zinc-900/40 border border-white/5 rounded-3xl p-6 md:p-8 backdrop-blur-md">
            <h2 className="text-xl font-serif font-bold text-white mb-4 flex items-center gap-2">
              <FileText className="h-5 w-5 text-emerald-400" />
              2. Content Submissions & IP
            </h2>
            <p className="text-zinc-400 text-sm leading-relaxed mb-4">
              By submitting articles to the Chronicle or adding productions to the archive, you grant Curtain Call a non-exclusive, royalty-free license to display and distribute that content on our platform. 
            </p>
            <p className="text-zinc-400 text-sm leading-relaxed">
              You represent and warrant that you own or have the necessary licenses, rights, and permissions to publish the content you submit. Articles completely generated by AI without original critical thought will be rejected without compensation.
            </p>
          </div>

          <div className="bg-zinc-900/40 border border-white/5 rounded-3xl p-6 md:p-8 backdrop-blur-md">
            <h2 className="text-xl font-serif font-bold text-white mb-4 flex items-center gap-2">
              <Scale className="h-5 w-5 text-amber-500" />
              3. Ticketing & Refunds
            </h2>
            <p className="text-zinc-400 text-sm leading-relaxed mb-4">
              Curtain Call acts as a ticketing intermediary for theatrical producers. All ticket sales are final. Refunds, cancellations, and exchanges are determined strictly by the individual production companies and not by Curtain Call, except in the event of a total show cancellation.
            </p>
            <p className="text-zinc-400 text-sm leading-relaxed">
              A standard 5% platform fee is applied to all ticketing transactions. Tickets are delivered digitally and must be presented at the venue.
            </p>
          </div>

          <div className="bg-zinc-900/40 border border-white/5 rounded-3xl p-6 md:p-8 backdrop-blur-md">
            <h2 className="text-xl font-serif font-bold text-white mb-4 flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-red-500" />
              4. Prohibited Conduct
            </h2>
            <p className="text-zinc-400 text-sm leading-relaxed">
              You agree not to use the platform to harass, defame, or abuse other users or artists. The abuse of the Verified Critic badge, creation of fake productions, ticket scalping, or automated scraping of our archive without explicit permission is strictly prohibited and will result in immediate permanent ban and possible legal action.
            </p>
          </div>

        </div>

        <div className="text-center py-6 border-t border-white/5">
          <p className="text-sm text-zinc-500">
            Curtain Call Ltd · 10 Glover Road, Ikoyi, Lagos
          </p>
        </div>
      </div>
    </div>
  );
}
